// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACuwTXww99TFyYtUeUVLu-hf_-o7mB7EQ',
    appId: '1:869873301662:web:3bd8a4863cc82ba38f638f',
    messagingSenderId: '869873301662',
    projectId: 'travelguru-9cf7d',
    authDomain: 'travelguru-9cf7d.firebaseapp.com',
    storageBucket: 'travelguru-9cf7d.appspot.com',
    measurementId: 'G-7SGL29DPQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP8DRRa4P8zgrp1qx9TFTcOVi_zz52jVQ',
    appId: '1:869873301662:android:45a8dbc742fb94ee8f638f',
    messagingSenderId: '869873301662',
    projectId: 'travelguru-9cf7d',
    storageBucket: 'travelguru-9cf7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLIE4dVORT5cjG0yJtHJbzLtbxgI4IIrw',
    appId: '1:869873301662:ios:8f2ef275e42a373c8f638f',
    messagingSenderId: '869873301662',
    projectId: 'travelguru-9cf7d',
    storageBucket: 'travelguru-9cf7d.appspot.com',
    iosClientId: '869873301662-10j85fb0k2pcgdavph1kp85d60mq03po.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelGuru',
  );
}
